### ISSUE TITLE
error at jekyll 4.0.0

### ISSUE THREAD

**Issue by vikke** [tocttou/hacker-blog#9]
i try to use this theme with jekyll(4.0.0).
but when build `jekyll serve`, it's occured error.

```
1: from /Users/vikke/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/external.rb:58:in `block in require_with_graceful_fail'
/Users/vikke/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/external.rb:73:in `rescue in block in require_with_graceful_fail': jekyll-sitemap (Jekyll::Errors::MissingDependencyException)
```

i installed jekyll-sitemap.
```
[master]$ gem list | grep jekyll
jekyll (4.0.0)
jekyll-feed (0.13.0)
jekyll-paginate (1.1.0)
jekyll-sass-converter (2.0.1)
jekyll-seo-tag (2.6.1)
jekyll-sitemap (1.4.0)
jekyll-watch (2.2.1)
```

help me please.

**Comment by tocttou** [comment]
Hey I tried the build with Jekyll 4.0.0

```
gem install jekyll-seo-tag
gem install jekyll-paginate
gem install jekyll-sitemap
```

```
jekyll (4.0.0, 3.8.6)
jekyll-feed (0.12.1)
jekyll-paginate (1.1.0)
jekyll-sass-converter (2.0.1, 1.5.2)
jekyll-seo-tag (2.6.1)
jekyll-sitemap (1.4.0)
jekyll-watch (2.2.1)
```

seems to work fine! could it be an issue with your paths?

**Comment by tocttou** [comment]
You can try `bundle exec jekyll serve` and see if it works?
